# Numpy

- 일반 List 대비 빠름
- 메모리 효율적
- 반복문 없이 배열에 대한 처리 지원
- 선형대수 관련 기능 제공

## ndarray

In [ ]:
import numpy as np

### Array Creation

In [13]:
# 데이터 타입이 하나로 통일된다
test_array = np.array([1,2,"3",4], float)    # (사용할 데이터 , 생성할 데이터 타입)
print(test_array)
type(test_array[3])   # 하나의 element가 차지하는 비트 : 64bit  

[1. 2. 3. 4.]


numpy.float64

\* 참고 \*
<br>
python에서는 2차원 배열은 얕은 복사가 되기 때문에 (주소값을 복사함)
<br>
copy.deepCopy()를 쓰자
<br>
numpy 같은경우 주소값 대신 데이터를 바로 쌓기 때문에 빠르다

In [16]:
import copy 

a = [[1,2,3,4],[5,6,7,8]]
b = a                    # 얕은 복사
c = copy.deepcopy(a)     # 깊은 복사
a[0][0] = 100
print("a : ",a)
print("b : ",b)
print("c : ",c)

a :  [[100, 2, 3, 4], [5, 6, 7, 8]]
b :  [[100, 2, 3, 4], [5, 6, 7, 8]]
c :  [[1, 2, 3, 4], [5, 6, 7, 8]]


### Shape

- 행렬의 차원을 표현
- tuple 타입 반환

In [22]:
# 비교
print(test_array.shape)
test_array2 = np.array([[1,2,3]], float)
print(test_array2.shape)

print("차원 : ",test_array2.ndim," , 데이터 개수 : ",test_array2.size)

(4,)
(1, 3)
차원 :  2  , 개수 :  3


### handling shape
<br>
** reshape **

In [39]:
#  ex) (2, 4) 배열을 (1, 8)로 바꾸는 경우
test_matrix = [[1,2,3,4],[5,6,7,8]]
np.array(test_matrix).reshape(8,)
np.array(test_matrix).reshape(-1,2,2)    # 차원의 개수를 잘 모를때 -1로 자동 설정

** flatten ** 
- 1차원 배열로 변경

In [36]:
np.array(test_matrix).flatten()

array([1, 2, 3, 4, 5, 6, 7, 8])

** indexing & slicing **
<br>
- indexing

In [41]:
a = np.array([[1,2,3],[4,5,6]], int)
print(a)
a[0,0] = 100
print(a[0][0])

[[1 2 3]
 [4 5 6]]
100


- slicing

In [44]:
b = np.array([[1,2,3],[4,5,6]], int)
b[:, 1:]    # 전체 row에서 1열 이상 데이터만
b[1, 1:3]   # 1 row에서 1열부터 3열 전까지

array([5, 6])

### creation function

In [45]:
np.arange(30)    # List의 range와 같음

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [46]:
np.arange(0, 10, 2)    # (start, end, step)

array([0, 2, 4, 6, 8])

In [48]:
# 0으로 초기화한 배열
np.zeros(shape=(5,2), dtype=np.int8)

array([[0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0]], dtype=int8)

In [49]:
# 1로 초기화한 배열
np.ones(shape=(10,), dtype=np.int8)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1], dtype=int8)

In [53]:
# 메모리 공간만 잡아줌 (초기화 안됨)
np.empty(shape=(10,))

array([2.37663529e-312, 2.05833592e-312, 2.05833592e-312, 2.18565567e-312,
       8.48798317e-313, 9.33678148e-313, 1.03977794e-312, 9.33678148e-313,
       1.06099790e-312, 6.97843598e+252])

##### something_like
- 기존 ndarray의 shape만큼 1, 0, empty 배열을 반환
- ones_like, zeros_like ...

In [57]:
test_matrix = np.arange(20).reshape(-1, 4)
np.zeros_like(test_matrix)

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

** identity **
- 단위 행렬

In [59]:
np.identity(n=3, dtype=np.int8)

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]], dtype=int8)

** eye **
- 대각선이 1인 행렬, 시작 인덱스 k 변경 가능

In [62]:
np.eye(N=3, M=6, k=2)

array([[0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.]])

- etc

In [66]:
test_matrix = np.arange(16).reshape(-1, 4)
np.diag(test_matrix)    # 대각 행렬의 값을 추출

array([ 0,  5, 10, 15])

In [68]:
# 균등 분포
np.random.uniform(0,1,10).reshape(2,5)

array([[0.19627788, 0.5041774 , 0.3436921 , 0.03128961, 0.10518568],
       [0.73606328, 0.66453795, 0.54423671, 0.70493088, 0.21573401]])

In [69]:
# 정규 분포
np.random.normal(0,1,10).reshape(2,5)

array([[ 1.18730861, -1.54309796, -0.38113373, -1.1562809 , -0.16238097],
       [ 0.30601583, -0.82540255, -0.19767692, -1.78977699, -0.0351353 ]])

In [70]:
sum(test_matrix)   #ndarray의 원소간의 합

array([24, 28, 32, 36])

##### axis
- 모든 연산의 기준이 되는 차원 축
- axis 값 예시
    - 1차원 배열 : column -> axis = 0
    - 2차원 배열 : row -> axis = 0, column -> axis = 1
    - 3차원 배열 : dimention -> axis = 0, row -> axis = 1, column -> axis = 2
    - 새로운 차원이 생길수록 한 기존 차원은 인덱스값이 밀린다

In [72]:
test_array = np.arange(1,13).reshape(3,4)
test_array.sum(axis=1), test_array.sum(axis=0)    
# row 기준 합 , column 기준 합 

(array([10, 26, 42]), array([15, 18, 21, 24]))

- concatenate

In [74]:
a = np.array([1,2,3])
b = np.array([2,3,4])
np.vstack((a,b))

array([[1, 2, 3],
       [2, 3, 4]])

In [78]:
a = np.array([[1],[2],[3]])
b = np.array([[2],[3],[4]])
np.hstack((a,b))

array([[1, 2],
       [2, 3],
       [3, 4]])

### array operation

In [79]:
test_a = np.array([[1,2,3],[4,5,6]], int)

In [81]:
test_a + test_a

array([[ 2,  4,  6],
       [ 8, 10, 12]])

In [82]:
test_a - test_a

array([[0, 0, 0],
       [0, 0, 0]])

In [83]:
test_a * test_a    # 같은 위치에 있는 값들끼리 연산. 단, shape이 같을때

array([[ 1,  4,  9],
       [16, 25, 36]])

##### Dot Product
- Matrix의 기본 연산

In [85]:
test_b = np.arange(1,7).reshape(2,3)
test_b = np.arange(7,13).reshape(3,2)

test_a.dot(test_b)

array([[ 58,  64],
       [139, 154]])

##### broadcasting

In [88]:
test = np.arange(1,16).reshape(3,5)
scalar = 100    # 모든 요소에 한 값을 더해주는게 broadcasting
test + scalar

array([[101, 102, 103, 104, 105],
       [106, 107, 108, 109, 110],
       [111, 112, 113, 114, 115]])

### comparisons

##### all & any

In [90]:
# all
a = np.arange(10)
a>5    # 일종의 broadcasting

array([False, False, False, False, False, False,  True,  True,  True,
        True])

In [91]:
# any
np.all(a>5), np.any(a>5)

(False, True)

##### logical

In [92]:
# logical : AND
np.logical_and(a>0, a<3)

array([False,  True,  True, False, False, False, False, False, False,
       False])

In [94]:
# logical : OR
np.logical_or(a>0, a>100)

array([False,  True,  True,  True,  True,  True,  True,  True,  True,
        True])

In [95]:
# logical : NOT
b = np.array([True, True, False])
np.logical_not(b)

array([False, False,  True])

##### np.where

In [96]:
# 조건이 맞으면 첫번째, 조건이 맞지않으면 두번째 출력
np.where(a>4, "크다", "작다")

array(['작다', '작다', '작다', '작다', '작다', '크다', '크다', '크다', '크다', '크다'],
      dtype='<U2')

##### argmax & argmin

In [98]:
a = np.arange(10)
np.argmax(a), np.argmin(a)

(9, 0)

##### boolean index
- 조건에 맞는 요소만 담아 새 배열 생성

In [99]:
test_array = np.arange(21)
test_array[test_array%2 == 0]    # 조건을 충족하는 요소만 담기
# where은 index를 추출, boolean은 data를 추출

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])